### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by krissrex** [Polarbirds/Polarbirds.com#1]
### We need a list of features

For the new site, there are many opportunities. Therefore, we need to chose:
- <b>Who</b> is the page made for?
- <b>How</b> should it be used?
- <b>What</b> should it be used to?

Previously the page was a nice excuse to put '<i>com.polarbirds.*</i>' as a package name when programming, or checking the TeamSpeak-app to see who were logged on. 
### But we can do better!

 What about allowing subdomains for private webpages?

> Eg.: <i>krissrex.polarbirds.com</i>, with the ability to redirect the ip to privately hosted webservers, like a laptop in my house.

Or how about using <i>polarbirds.com</i> as the TeamSpeak IP again?

Image hosting? 

> We all know tronds neat program that hosts on <i>folk.ntnu.no</i>. Why not allow such hosting on <i>polarbirds.com</i> as well? Possibly on a subdomain <i>img.polarbirds.com</i> or folder <i>polarbirds.com/img</i>

Software publishing site?

> Many of the PB-guys like to program. So why not allow for hosting the created software? I (krissrex) made "CodeCloud" as a project in IT1, and it showed me that it is not such a hassle to develop.

Meetup calendar?

> Why not add suggestions for events in a calendar? We already got facebook to arrange meeting, though.

High Score table?

> If we ever make games with highs cores, the game could get its own entry on a high score page. Thus you could browse all high scores from all games on the same page.

Muncher(?), the game and statistics-tracker for Munchkin!

> A tracker that tracks levels, deaths, wins and other stats across all our munchkin-matches! Can also show statistics in form of histograms, cake diagrams and more!
### I want your suggestions!

These were just the thoughts from the top of my head. I want <b>YOU</b> (think uncle sam-picture now) to give your opinion!

**Comment by haraldfw** [comment]
The previously mentioned munchkin-program(level-counter + statistics-/game-tracker) should be hosted here! On something like counter.polarbirds.com or muncher.polarbirds.com

**Comment by krissrex** [comment]
Preferably on polarbirds.com/muncher (or whatever name it will be), as a new subdomain may result in a technically more difficult solution. I prefer subdomains for when the host is a physically different computer or different server process/application (eg. a different instance of apache or nodejs).
